# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - monago

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm ci
    - run: npm run build
    - run: ls dist/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://monago.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ab0c5fdca99e4096a8dae41c72ebf2e7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ddfcae8f9a654e00bdf409976a1ac594 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        tags: monago.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ab0c5fdca99e4096a8dae41c72ebf2e7 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'monago'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f680ad2928b1440c9e77fa0e960b15bf }}
        images: 'monago.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ab0c5fdca99e4096a8dae41c72ebf2e7 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'